# Generated by Django 5.2 on 2026-02-04 00:35

import Social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social", "0053_storyimage_storyvideo_delete_storymedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="expires_at",
            field=models.DateTimeField(default=Social.models.default_story_expiration),
        ),
    ]
