# Generated by Django 5.2 on 2026-02-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Social", "0054_alter_story_expires_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="comments",
        ),
    ]
