# Generated by Django 5.2 on 2026-02-21 00:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0031_remove_times_box_remove_times_creator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name_team")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Descripion"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FITNESS", "FITNESS"),
                            ("SCALED", "SCALED"),
                            ("AMADOR", "AMADOR"),
                            ("RX", "RX"),
                            ("MASTER", "MASTER"),
                        ],
                        default="EXPERIMENTAL",
                        verbose_name="category_team",
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        default="DEFAULT",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.box",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_team",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator Team",
                    ),
                ),
                (
                    "membros",
                    models.ManyToManyField(
                        related_name="team_members",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="members",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team_Achievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement",
                    models.CharField(max_length=200, verbose_name="achievement"),
                ),
                (
                    "placement",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="placement",
                    ),
                ),
                (
                    "current_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Team.team",
                        verbose_name="team_achievements",
                    ),
                ),
            ],
        ),
    ]
