# Generated by Django 5.2 on 2026-04-01 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name_team")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Descripion"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FITNESS", "FITNESS"),
                            ("SCALED", "SCALED"),
                            ("AMADOR", "AMADOR"),
                            ("RX", "RX"),
                            ("MASTER", "MASTER"),
                        ],
                        default="EXPERIMENTAL",
                        verbose_name="category_team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team_Achievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement",
                    models.CharField(max_length=200, verbose_name="achievement"),
                ),
                (
                    "placement",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="placement",
                    ),
                ),
            ],
        ),
    ]
