# Generated by Django 5.2 on 2026-02-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Team", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="membros",
            new_name="members",
        ),
    ]
