# Generated by Django 5.2 on 2026-04-01 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Team", "0001_initial"),
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="box",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.box",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_team",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator Team",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="team_members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="members",
            ),
        ),
        migrations.AddField(
            model_name="team_achievements",
            name="current_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Team.team",
                verbose_name="team_achievements",
            ),
        ),
    ]
