# Generated by Django 5.2 on 2026-04-01 00:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("WOD", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "box_name",
                    models.CharField(max_length=20, verbose_name="Nome da BOX"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("MASCULINO", "MASCULINO"),
                            ("FEMININO", "FEMININO"),
                            ("NÃO-ESPECIFICAR", "NÃO-ESPECIFICAR"),
                        ],
                        default="NÃO-ESPECIFICAR",
                        verbose_name="Genero",
                    ),
                ),
                ("view_weight", models.BooleanField(default=True)),
                ("view_height", models.BooleanField(default=True)),
                ("view_category", models.BooleanField(default=True)),
                ("view_box", models.BooleanField(default=True)),
                ("view_personal_record", models.BooleanField(default=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media_profile",
                        verbose_name="Foto Perfil",
                    ),
                ),
                (
                    "created_at_profile",
                    models.DateField(auto_now=True, verbose_name="Data Adessão"),
                ),
                (
                    "birthday",
                    models.DateField(
                        default=django.utils.timezone.now,
                        max_length=50,
                        verbose_name="Aniversário",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MaxValueValidator(300),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="Peso",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Altura"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FITNESS", "FITNESS"),
                            ("SCALED", "SCALED"),
                            ("AMADOR", "AMADOR"),
                            ("RX", "RX"),
                            ("MASTER", "MASTER"),
                        ],
                        default="EXPERIMENTAL",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "is_coach",
                    models.BooleanField(default=False, verbose_name="Coach ? "),
                ),
                (
                    "box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box",
                        to="account.box",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilePersonalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.now, max_length=50),
                ),
                (
                    "personal_record",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MaxValueValidator(500),
                            django.core.validators.MinValueValidator(5),
                        ],
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moviment",
                    models.ForeignKey(
                        default="NONE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WOD.movement",
                    ),
                ),
            ],
        ),
    ]
