# Generated by Django 5.2 on 2025-10-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='box',
            field=models.CharField(choices=[('CF4TIME CAMPINA ', 'CF4TIME CAMPINA'), ('CF4TIME CAMPINA', 'CF4TIME JOCKEY')], default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='times',
            name='category',
            field=models.CharField(choices=[('FITNESS', 'FITNESS'), ('SCALED', 'SCALED'), ('AMADOR', 'AMADOR'), ('RX', 'RX'), ('MASTER', 'MASTER')], default='EXPERIMENTAL'),
        ),
    ]
