# Generated by Django 5.2 on 2025-10-11 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_times_box_times_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='membros',
            field=models.ManyToManyField(related_name='membros', to=settings.AUTH_USER_MODEL),
        ),
    ]
