# Generated by Django 5.2 on 2025-10-21 23:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_box'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, max_length=50, verbose_name='Aniversário'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='box',
            field=models.ForeignKey(blank=True, default='DEFAULT', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.box'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('FITNESS', 'FITNESS'), ('SCALED', 'SCALED'), ('AMADOR', 'AMADOR'), ('RX', 'RX'), ('MASTER', 'MASTER')], default='EXPERIMENTAL', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at_profile',
            field=models.DateField(auto_now=True, verbose_name='Data Adessão'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genre',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO'), ('NÃO-ESPECIFICAR', 'NÃO-ESPECIFICAR')], default='NÃO-ESPECIFICAR', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_coach',
            field=models.BooleanField(default=False, verbose_name='Coach ? '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media_profile', verbose_name='Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)], verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='times',
            name='box',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, to='account.box'),
        ),
        migrations.AlterField(
            model_name='times',
            name='category',
            field=models.CharField(choices=[('FITNESS', 'FITNESS'), ('SCALED', 'SCALED'), ('AMADOR', 'AMADOR'), ('RX', 'RX'), ('MASTER', 'MASTER')], default='EXPERIMENTAL', verbose_name='Categoria do Time'),
        ),
        migrations.AlterField(
            model_name='times',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador do Time'),
        ),
        migrations.AlterField(
            model_name='times',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='times',
            name='membros',
            field=models.ManyToManyField(related_name='times_membros', to=settings.AUTH_USER_MODEL, verbose_name='Membros'),
        ),
    ]
