# Generated by Django 5.2 on 2026-01-21 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0028_alter_profile_birthday_alter_profile_box_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="times",
            name="achievements",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Conquistas do time"
            ),
        ),
        migrations.AddField(
            model_name="times",
            name="placement",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Colocação em Competições",
            ),
        ),
        migrations.AlterField(
            model_name="times",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Time_name"),
        ),
    ]
