# Generated by Django 5.2 on 2026-01-21 00:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0029_times_achievements_times_placement_alter_times_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="times",
            name="achievements",
        ),
        migrations.RemoveField(
            model_name="times",
            name="placement",
        ),
        migrations.CreateModel(
            name="Time_Achievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement",
                    models.CharField(max_length=200, verbose_name="Conquista"),
                ),
                (
                    "placement",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Colocação em Competições",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.times",
                        verbose_name="Time_Conquista",
                    ),
                ),
            ],
        ),
    ]
