# Generated by Django 5.2 on 2026-02-21 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0030_remove_times_achievements_remove_times_placement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="times",
            name="box",
        ),
        migrations.RemoveField(
            model_name="times",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="times",
            name="membros",
        ),
        migrations.DeleteModel(
            name="Time_Achievements",
        ),
        migrations.DeleteModel(
            name="Times",
        ),
    ]
