# Generated by Django 5.2 on 2026-02-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0032_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="box",
            field=models.ForeignKey(
                blank=True,
                default="DEFAULT",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box",
                to="account.box",
            ),
        ),
    ]
