# Generated by Django 5.2 on 2026-04-01 00:16

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("link", models.URLField(blank=True, max_length=100, null=True)),
                ("text", models.CharField(blank=True, max_length=3000, null=True)),
                (
                    "date_initial",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2026, 4, 1, 0, 16, 55, 987962, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2026, 4, 1, 0, 16, 55, 987982, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "price",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events_participating",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
