# Generated by Django 5.2 on 2025-10-11 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0070_alter_event_date_end_alter_event_date_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 11, 19, 37, 25, 355478, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 11, 19, 37, 25, 355465, tzinfo=datetime.timezone.utc)),
        ),
    ]
