# Generated by Django 5.2 on 2025-11-14 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0077_alter_event_date_end_alter_event_date_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 21, 29, 39, 629105, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 21, 29, 39, 629086, tzinfo=datetime.timezone.utc)),
        ),
    ]
