# Generated by Django 5.2 on 2025-11-25 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0079_alter_event_date_end_alter_event_date_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 0, 25, 52, 108585, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 0, 25, 52, 108567, tzinfo=datetime.timezone.utc)),
        ),
    ]
