# Generated by Django 5.2 on 2026-02-04 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0085_alter_event_date_end_alter_event_date_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 4, 0, 33, 56, 465240, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_initial',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 4, 0, 33, 56, 465222, tzinfo=datetime.timezone.utc)),
        ),
    ]
