# Generated by Django 5.2 on 2026-02-21 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0087_alter_event_date_end_alter_event_date_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 21, 0, 29, 39, 924797, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_initial",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 21, 0, 29, 39, 924775, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
