# Generated by Django 5.2 on 2026-02-25 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0088_alter_event_date_end_alter_event_date_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 25, 21, 36, 22, 469013, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_initial",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 25, 21, 36, 22, 468983, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
