# Generated by Django 5.2 on 2026-02-25 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0089_alter_event_date_end_alter_event_date_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 25, 22, 21, 38, 553764, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_initial",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 25, 22, 21, 38, 553746, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
