# Generated by Django 5.2 on 2026-02-28 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0090_alter_event_date_end_alter_event_date_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 1, 24, 52, 167949, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_initial",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 1, 24, 52, 167931, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
