# Generated by Django 5.2 on 2026-02-28 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0092_alter_event_date_end_alter_event_date_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 17, 8, 26, 816531, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_initial",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 17, 8, 26, 816511, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
