# Generated by Django 5.2 on 2026-03-16 21:54

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0093_alter_event_date_end_alter_event_date_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date_create",
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="events_participating",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 16, 21, 54, 41, 346773, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_initial",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 16, 21, 54, 41, 346754, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
