# Generated by Django 5.2 on 2026-03-16 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0094_remove_event_date_create_event_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="local",
            new_name="location",
        ),
        migrations.AlterField(
            model_name="event",
            name="date_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 16, 22, 59, 48, 643973, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_initial",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 16, 22, 59, 48, 643955, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
