# Generated by Django 5.2 on 2026-04-01 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AmrapResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rounds", models.PositiveIntegerField()),
                ("reps", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="EmomResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rounds_completed", models.PositiveIntegerField()),
                ("failed_minute", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ForTimeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_seconds", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MovementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("requires_load", models.BooleanField(default=False)),
                ("requires_reps", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="WOD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description_wod", models.TextField(max_length=10000)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FOR_TIME", "FOR TIME"),
                            ("AMRAP", "AMRAP"),
                            ("EMOM", "EMOM"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Duração em minutos (AMRAP/EMOM)",
                        null=True,
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("date", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WodMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reps", models.IntegerField()),
                (
                    "load",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Ex: RX / Scaled / Observações",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WodResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=2000)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WOD.movementtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reps_expected", models.IntegerField()),
                (
                    "load_expected",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("reps_done", models.IntegerField(blank=True, null=True)),
                (
                    "load_used",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WOD.movement"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
