# Generated by Django 5.2 on 2026-04-01 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("WOD", "0001_initial"),
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wod",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wods_created",
                to="account.profile",
            ),
        ),
        migrations.AddField(
            model_name="wod",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="liked_wods", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="wodmovement",
            name="movement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="WOD.movement"
            ),
        ),
        migrations.AddField(
            model_name="wodmovement",
            name="wod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="WOD.wod",
            ),
        ),
        migrations.AddField(
            model_name="wodresult",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wod_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wodresult",
            name="wod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="WOD.wod",
            ),
        ),
        migrations.AddField(
            model_name="resultmovement",
            name="wod_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="WOD.wodresult",
            ),
        ),
        migrations.AddField(
            model_name="fortimeresult",
            name="wod_result",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="for_time",
                to="WOD.wodresult",
            ),
        ),
        migrations.AddField(
            model_name="emomresult",
            name="wod_result",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emom",
                to="WOD.wodresult",
            ),
        ),
        migrations.AddField(
            model_name="amrapresult",
            name="wod_result",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amrap",
                to="WOD.wodresult",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wodmovement",
            unique_together={("wod", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="wodresult",
            unique_together={("user", "wod")},
        ),
        migrations.AlterUniqueTogether(
            name="resultmovement",
            unique_together={("wod_result", "order")},
        ),
    ]
