# Generated by Django 5.2 on 2025-11-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOD', '0005_remove_wod_created_at_wod_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wod',
            old_name='amauter',
            new_name='amauter_fem',
        ),
        migrations.RenameField(
            model_name='wod',
            old_name='elite',
            new_name='amauter_masc',
        ),
        migrations.RenameField(
            model_name='wod',
            old_name='fit',
            new_name='elite_fem',
        ),
        migrations.RenameField(
            model_name='wod',
            old_name='rx',
            new_name='elite_masc',
        ),
        migrations.RenameField(
            model_name='wod',
            old_name='scaled',
            new_name='fit_fem',
        ),
        migrations.AddField(
            model_name='wod',
            name='fit_masc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wod',
            name='rx_fem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wod',
            name='rx_masc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wod',
            name='scaled_fem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wod',
            name='scaled_masc',
            field=models.IntegerField(default=0),
        ),
    ]
