# Generated by Django 5.2 on 2026-01-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WOD", "0006_rename_amauter_wod_amauter_fem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wod",
            name="amauter_fem",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="amauter_masc",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="elite_fem",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="elite_masc",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="fit_fem",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="fit_masc",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="rx_fem",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="rx_masc",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="scaled_fem",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="scaled_masc",
        ),
    ]
